name: CI

on:
  push:
    branches:
    - main
  schedule:
  - cron: "0 2 * * *"

jobs:
  gnu:
    name: Process the GNU test results
    runs-on: ubuntu-latest
    steps:
    - name: Install deps
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install jq python3-pandas python3-matplotlib

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Download the result
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: GNU.yml
        name: gnu-result
        repo: uutils/coreutils
        path: dl

    - name: Merge the json files
      shell: bash
      run: |
       echo "== dl/gnu-result.json =="
       cat dl/gnu-result.json
       echo "== gnu-result.json =="
       cat gnu-result.json
       jq -s '.[0] * .[1]' gnu-result.json dl/gnu-result.json > merged.json
       echo "== merged.json ="
       cat merged.json
       mv merged.json gnu-result.json
       git commit -m "Update of the results" .
       rm -rf dl

    - name: Generate the graph
      shell: bash
      run: |
        python graph.py gnu-result.json

    - name: Add & Commit the graph
      uses: EndBug/add-and-commit@v7.2.1
      with:
        default_author: github_actions
        message: "Refresh the graph"
        add: gnu-results.png
